services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8123:8123"
    volumes:
      - ./home_assistant_data:/config
      - /etc/localtime:/etc/localtime:ro
      # Mount the MinderGas integration directly for development
      - ./custom_components/mindergas:/config/custom_components/mindergas:ro
    networks:
      - home-assistant-net

networks:
  home-assistant-net:
    driver: bridge
